Module2 task1
htmlacademy-adaptive/1892993-sedona-27 pull request #2
Opened 2022-11-27 21:39 UTC by WhiteShark23

Добавлена разметка всех страниц

2022-11-29 19:58 UTC, WhiteShark23 commented
Добавлена разметка

2022-12-04 16:32 UTC, GennadiyM requested changes

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +    <header class="main-header">
page__header main-header

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +      <nav class="main-nav">
main-header__main-nav main-nav

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +    </div>
и что это за живущая отдельно от всего сущность. Ни в шапке, ни в mainе?

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +    <main class="page__main main">
main class="page__main" достаточно этого

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +      </div>
взял и оторвал от секции информацию

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +      <section class="photo video">
а вот и осиротевшая без заголовка и описания секция

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +            </div>
и что тут не будет ни одной ссылки?

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +      <section class="photo video">
ну во первых или фото или видео, во вторых как то странно звучит что блок с кучей photo внутри назвается как просто фотография (единственно число, одна фотка).

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +            </div>
вот где нужно было класс photo использовать

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +            <img src="#" alt="асфальтированная дорога в гуще леса с серпантиннами">
в домашке было написано как вставлять картинки на данном этапе

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +            <img src="#" alt="асфальтированная дорога в гуще леса с серпантиннами">
у картинки не проставлены width и height

2022-12-04 16:32 UTC, GennadiyM commented on source/catalog.html
> +              <button class="photo__like-button" type="button"></button>
где подпись у кнопки (aria-label)

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +      </div>
какие-то оторванные от реальности блоки

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +              <span class="name-data__desc">ИМЯ*:</span>
uppercase в разметке

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +              <span class="name-data__desc">ФАМИЛИЯ*:</span>
uppercase в разметке

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +        <form class="form-recall" action="#">
method?

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +      </div>
зачем ей обертка в виде div

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +      </ul>
а тут куда ссылки потерялись?

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +      <ul class="footer__social social--list social">
зачем здесь модификатор social--list

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +      </div>
зачем ссылке лишняя обертка в виде div

2022-12-04 16:32 UTC, GennadiyM commented on source/form.html
> +            </ul>
Ну и куда делись знания с прошлого потока? Мы чекбоксы и радиокнопки делали отдельными блоками????

2022-12-08 16:38 UTC, merged